parser: babel-eslint
extends: airbnb
env:
  browser: true
  node: true
settings:
  import/resolver:
    webpack:
      config: _webpack/common.js
globals:
  NODE_ENV: true
  GRAPHQL: true
  GOOGLEID: true
  GOOGLEREDIRECTURI: true
  GOOGLESCOPE: true
rules:
  semi:
  - error
  - never
  arrow-body-style: 0
  global-require: 0
  no-console: 0
  no-param-reassign: 0
  no-extra-boolean-cast: 0
  max-len:
  - error
  - 160
  no-confusing-arrow: 0
  import/prefer-default-export: 0
  import/no-extraneous-dependencies:
  - error
  - devDependencies: true
